# Generated by Django 4.2.6 on 2024-03-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mng_app', '0009_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
