# Generated by Django 4.2.6 on 2024-05-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mng_app', '0013_attendencerecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendenceRecord',
        ),
    ]
